name: Fetch DSE Screener

concurrency:
  group: dse-screener
  cancel-in-progress: false

on:
  schedule:
    # Run Sun–Thu at 04:00 UTC (10:00 in Bangladesh)
    - cron: "0 4 * * 0-4"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          PYTHONUNBUFFERED: "1" # ensures logs are flushed immediately
        run: |
          python scripts/fetch_dse.py

      # Option A: commit the CSV into the repo
      - name: Commit CSV (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Daily DSE screener data"
            git push
          fi

      # Option B (optional): also upload as run artifact
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: dse-screener-csv
          path: data/*.csv
